CREATE TABLE IF NOT EXISTS EMPLOYEES(
    EMPLOYEE_ID TEXT,
    FIRST_NAME TEXT,
    DEPARTMENT TEXT,
    SALARY REAL
);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, DEPARTMENT, SALARY) VALUES
('1', 'John', 'Sales', 50000),
('2', 'Jane', 'Marketing', 60000),
('3', 'Doe', 'IT', 75000),
('4', 'Alice', 'HR', 55000),
('5', 'Bob', 'Finance', 70000);

SELECT SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES;

SELECT AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES;

SELECT COUNT(DISTINCT DEPARTMENT) AS DEPARTMENT_COUNT
FROM EMPLOYEES;

SELECT MIN(SALARY) AS MINIMUM_SALARY
FROM EMPLOYEES;

SELECT MAX(SALARY) AS MAXIMUM_SALARY
FROM EMPLOYEES;